---
apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-config
  namespace: grpc
data:
  envoy.yaml: "static_resources:\n  listeners:\n  - address:\n      socket_address:\n
    \       address: 0.0.0.0\n        port_value: 8443\n    filter_chains:\n    -
    filters:\n      - name: envoy.http_connection_manager\n        typed_config:\n
    \         \"@type\": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager\n
    \         stat_prefix: ingress_http\n          route_config:\n            virtual_hosts:\n
    \           - name: default\n              domains: [\"*\"]\n              routes:\n
    \             - match: {path: \"/healthz\"}\n                direct_response:\n
    \                 status: 200\n              - match: {prefix: \"/\"}\n                route:\n
    \                 cluster: local_cluster\n                  timeout: 0s \n                  idle_timeout:
    0s\n                  max_stream_duration:\n                    grpc_timeout_header_max:
    5s\n          http_filters:\n          - name: envoy.filters.http.router\n            typed_config:\n
    \             \"@type\": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router\n
    \         access_log:\n          - name: envoy.access_loggers.file\n            typed_config:\n
    \             \"@type\": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog\n
    \             path: \"/dev/stdout\"\n      transport_socket:\n        name: envoy.transport_sockets.tls\n
    \       typed_config:\n          \"@type\": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext\n
    \         common_tls_context:\n            tls_certificates:\n            - certificate_chain:
    {filename: \"/etc/certs/tls.crt\"}\n              private_key: {filename: \"/etc/certs/tls.key\"}\n
    \           alpn_protocols: h2\n  clusters:\n  - name: local_cluster\n    http2_protocol_options:
    {}\n    connect_timeout: 1s\n    type: static\n    lb_policy: round_robin\n    load_assignment:\n
    \     cluster_name: local_cluster\n      endpoints:\n      - lb_endpoints:\n        -
    endpoint:\n            address:\n              socket_address:\n                address:
    127.0.0.1\n                port_value: 9001\n"
